language: node_js
node_js:
  - node
before_script:
  - make tests
addons:
  apt:
    packages:
    - xvfb
install:
  - npm install
  - mkdir -p ~/.config/Electron
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
